### ISSUE TITLE
CI tests failing not finding libmediapipe_c

### ISSUE THREAD

**Issue by sr229** [vignetteapp/Akihabara#15]
CI seems to be in working order however tests are failing because it's missing `libmediapipe_c.so` or `libmediapipe_c.dll`.

**Comment by adryzz** [comment]
move/symlink the build artifact (.so) into /src/Akihabara.Tests/bin/net5.0/Debug after the dotnet build

**Comment by sr229** [comment]
> move/symlink the build artifact (.so) into /src/Akihabara.Tests/bin/net5.0/Debug after the dotnet build

This should be automated, and not something to be done manually, especially if contributor expects this to be automatically done.

**Comment by adryzz** [comment]
yes, i meant add it as another step in the CI
