### ISSUE TITLE
About Copyright Notice

### ISSUE THREAD

**Issue by homuler** [vignetteapp/Akihabara#18]
It appears that most of the source code has been copied from [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) and published without any license indication, and this violates [its LICENSE](https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/LICENSE#L12-L13).

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

We would like to see at least a license notice, and preferably at the top of each source code copy.

P.S.
You are welcome to copy and reuse it, and you may ask me if you have any questions about the source code.

**Comment by sr229** [comment]
Heya, we're working on this, we promptly forgot to do the notices since we haven't finished the entire library yet (aka it's not entirely public) so forgive us for that oversight. It'll be added soon though!

Thanks for letting us know.

**Comment by homuler** [comment]
Thank you for your prompt reply.

> so forgive us for that oversight. It'll be added soon though!

As long as you fix it, I'm in no hurry.
Also, if you find any bugs, I'd appreciate it if you let me know!

Actually, it would have been nice if we could have helped in some way...well, I guess there's a namespace issue though, haha.

**Comment by Speykious** [comment]
Thank you!

Yes, we have run into bugs with our most complete fork right now, which is [here](https://github.com/Speykious/Akihabara/tree/fix-lib).
While we didn't manage to automatically build `libmediapipe_c.{so,dll}` for ourselves yet, we have built it using your own MediapipeUnityPlugin repo and have been able to test the library with it.
Most unit tests have worked, but we are now running into a seemingly very low-level issue which we probably have to fix before the library is fully complete.

We would gladly appreciate your help on this! Here is our discord server:
https://discord.gg/YUts9qYYuT

**Comment by sr229** [comment]
Notices added now along with a editorconfig rule so we don't forgor again :D.

**Comment by homuler** [comment]
I don't know which channel to use, so I'll just write a comment here.

To fix [the build error](https://github.com/Speykious/Akihabara/runs/3640291949), you need to change all the namespaces specified in proto files at mediapipe repo, so I think you need to fix https://github.com/vignetteapp/Akihabara/blob/80902fe9a9f5e79de00e4e1e16c06125d40ef895/third_party/proto_namespace.diff .

In fact, I commented out [this line](https://github.com/vignetteapp/Akihabara/blob/80902fe9a9f5e79de00e4e1e16c06125d40ef895/WORKSPACE#L49), build process has succeeded on my local machine (probably test will fail, though).

**Comment by Speykious** [comment]
Oh! No, it wasn't already known. I'll make an issue on that.
