### ISSUE TITLE
Rename project to Mediapipe

### ISSUE THREAD

**Issue by sr229** [vignetteapp/Akihabara#24]
Now that we're close to being released, at post-Debut for Vignette, we would want to rename it as `Mediapipe` simply instead, then focus our attention in merging our work with the main MediaPipeUnity project and just focus as one group.

As such here's some of the TODOs we can do at the Encore roadmap:

- [ ] rename the project to simply `Mediapipe`.

**Comment by adryzz** [comment]
I think we can close this in favor of project Ayase

**Comment by sr229** [comment]
> I think we can close this in favor of project Ayase

Based on our Discord discussion, we will proceed with the rename, Ayase will be a different effort altogether.
