### ISSUE TITLE
Buffer sizes inconsistent

### ISSUE THREAD

**Issue by adryzz** [vignetteapp/Akihabara#32]
![](https://cdn.discordapp.com/attachments/881216118155518013/892043675964698644/unknown.png)

**Comment by sr229** [comment]
The worst part is we're not really sure why this happens, I doubt it's a marshaling error so why are we missing one byte?

**Comment by homuler** [comment]
It's intended. It tests if an exception will be thrown.
https://github.com/vignetteapp/Akihabara/blob/2b1d1915de72480c40e95ba5eb43013d83e19e84/src/Akihabara.Tests/Framework/ImageFormat/ImageFrameTest.cs#L153

At least, this test should have `SignalAbortAttibute`, but still I don't know why SIGABRT isn't handled on Linux.

**Comment by sr229** [comment]
It should be handled on Linux properly given we actually did the signal properly per the POSIX specification, so I'm not sure why aren't we catching it well.

**Comment by homuler** [comment]
I think default signal handler will crash the whole program.
We need to overwrite the handler to avoid crash, but it seems it fails.

**Comment by Speykious** [comment]
On my machine, it seems like it's caught, but only *sometimes* for some reason. As @homuler suggested, I'm gonna build `libmediapipe_c` with debug flags and look at the core dump to see if we can do anything about it.

**Comment by sr229** [comment]
@Speykious I assume this is resolved now?

**Comment by Speykious** [comment]
Yes, it is. The problem was actually what Homuler highlighted in PR #34 and not this, as the buffer sizes are meant to be inconsistent in the tests.
